services:
#  add the authorization-server service. Create an image and push to Docker hub
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8084:8084"  # Change the host port to 8084
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?authSource=admin&authMechanism=SCRAM-SHA-1

  reactive-mongodb:
    image: toppertje1966/reactive-mongodb:latest
    ports:
      - "8083:8083"
    depends_on:
      - mongo
